# nxapi — Nintendo Switch Online API client. Publishes your Switch activity to
# Discord as Rich Presence. Not in nixpkgs; upstream is
# https://gitlab.fancy.org.uk/samuel/nxapi and it ships to npm.
{
  lib,
  buildNpmPackage,
  fetchurl,
}:
buildNpmPackage rec {
  pname = "nxapi";
  version = "1.6.1";

  # The npm tarball, not the git tree. Two reasons:
  #  1. `dist/` is already compiled in it, so there is no rollup/TypeScript
  #     build step and no need for the ~30 devDependencies (which include
  #     Electron — a large, awkward thing to fetch for a CLI you never run the
  #     GUI of).
  #  2. npm tarballs are byte-stable and npm publishes their SRI hash, so the
  #     hash below is exact rather than something you have to discover.
  src = fetchurl {
    url = "https://registry.npmjs.org/nxapi/-/nxapi-${version}.tgz";
    hash = "sha512-fh0S2ztLWIus/M59YUltfhwZcH7yONwSP5mkujVpc3Ika0dKJhTfRuWdPu9OknQXBqDTsaUbIwC4cbrsxiCNcA==";
  };

  # npm tarballs carry no lockfile, and buildNpmPackage requires one. Both
  # ./package.json and ./package-lock.json are vendored here. To regenerate on a
  # version bump, do all of this — the steps are not independent:
  #
  #   # 1. the manifest, minus devDependencies (Electron, React, rollup — none
  #   #    of which a CLI with a prebuilt dist/ needs)
  #   tar xzOf nxapi-<v>.tgz package/package.json \
  #     | jq 'del(.devDependencies, .scripts)' > package.json
  #
  #   # 2. the lockfile — with NIXPKGS' npm, not your distro's. This matters:
  #   #    npm 12 silently drops discord-rpc's optional git dependency
  #   #    `register-scheme`, npm 11 keeps it, and `npm ci` inside the build
  #   #    uses whichever npm nixpkgs ships. A lock generated by the wrong npm
  #   #    fails with "Missing: register-scheme@ from lock file".
  #   nix shell nixpkgs#nodejs -c npm install --package-lock-only --ignore-scripts
  #
  #   # 3. patch that git dependency back out. register-scheme registers URL
  #   #    schemes on Windows and macOS and does nothing on Linux, but it is a
  #   #    native addon pulled over git+ssh, which prefetch-npm-deps refuses
  #   #    without forceGitDeps. Dropping it from the lock — including
  #   #    discord-rpc's optionalDependencies field, which is what makes npm
  #   #    look for it — is nixpkgs' own suggested fix, and `npm ci` then
  #   #    installs the same 126 packages it would have anyway.
  #   jq 'del(.packages["node_modules/register-scheme"],
  #           .packages["node_modules/bindings"],
  #           .packages["node_modules/node-addon-api"],
  #           .packages["node_modules/file-uri-to-path"],
  #           .packages["node_modules/discord-rpc"].optionalDependencies)' \
  #      package-lock.json > tmp && mv tmp package-lock.json
  #
  # The files are copied rather than edited in place because buildNpmPackage
  # runs this same postPatch inside fetchNpmDeps, a separate derivation that
  # does NOT inherit nativeBuildInputs — so jq is not available there. Copying
  # needs nothing but coreutils.
  postPatch = ''
    cp ${./package.json} package.json
    cp ${./package-lock.json} package-lock.json
  '';

  # ⚠ FILL THIS IN ONCE, ON THE FIRST BUILD.
  # Nix cannot know the hash of the npm dependency set until it has fetched it.
  # Build, let it fail, and paste the "got:" value it prints:
  #
  #   nix build .#nxapi 2>&1 | grep -A2 'got:'
  #
  # Or run ../../scripts/update-hashes.sh, which does exactly that.
  npmDepsHash = "sha256-h5FLmY9kh76VbIlL2EYOcfhTq+GAa4Nub2+dfs6eYoc=";

  # dist/ is prebuilt in the tarball and there is no build script to run.
  dontNpmBuild = true;

  meta = {
    description = "Nintendo Switch Online API client with Discord Rich Presence";
    homepage = "https://gitlab.fancy.org.uk/samuel/nxapi";
    license = lib.licenses.agpl3Plus;
    platforms = lib.platforms.linux;
    mainProgram = "nxapi";
  };
}
